name: Testare

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: bugtracker_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Run Spring Boot Tests
        working-directory: ./BugReporter-backend
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/bugtracker_test
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: password
        run: mvn test

  cypress-tests:
    needs: backend-tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Start Spring Boot Application
        working-directory: ./BugReporter-backend
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/bugtracker_test
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: postgres
        run: mvn spring-boot:run &

      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./BugReporter-frontend
          install-command: npm install
          start: npm run dev
          wait-on: 'http://localhost:5173'
          browser: edge